"""
Report repository — database access layer for reports table.

Architecture:
  ReportService → ReportRepository → PostgreSQL

Reports are append-mostly: status updates happen but records are never
deleted. The Celery worker calls update_status() when generation finishes.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.report import Report, ReportStatus


class ReportRepository:
    """Handles all database operations for the reports table."""

    def __init__(self, session: AsyncSession) -> None:
        """Inject the async database session."""
        self._session = session

    async def create(self, report: Report) -> Report:
        """
        Persist a new Report record.

        The caller must commit after calling this method.
        """
        self._session.add(report)
        await self._session.flush()
        await self._session.refresh(report)
        return report

    async def get_by_id(self, report_id: uuid.UUID) -> Report | None:
        """Return a Report by UUID, or None if not found."""
        result = await self._session.execute(select(Report).where(Report.id == report_id))
        return result.scalar_one_or_none()

    async def list_by_user(
        self,
        user_id: uuid.UUID,
        *,
        limit: int = 20,
        offset: int = 0,
    ) -> list[Report]:
        """
        Return paginated reports for a specific user (generated_by = user_id).

        Args:
            user_id: The user's UUID.
            limit:   Maximum records to return (capped at 100).
            offset:  Pagination offset.
        """
        effective_limit = min(max(limit, 1), 100)
        result = await self._session.execute(
            select(Report)
            .where(Report.generated_by == user_id)
            .order_by(Report.created_at.desc())
            .limit(effective_limit)
            .offset(offset)
        )
        return list(result.scalars().all())

    async def list_all(
        self,
        *,
        limit: int = 20,
        offset: int = 0,
    ) -> list[Report]:
        """Return all reports ordered by created_at desc (admin use)."""
        effective_limit = min(max(limit, 1), 100)
        result = await self._session.execute(
            select(Report).order_by(Report.created_at.desc()).limit(effective_limit).offset(offset)
        )
        return list(result.scalars().all())

    async def count_by_user(self, user_id: uuid.UUID) -> int:
        """Return total reports generated by this user."""
        from sqlalchemy import func

        result = await self._session.execute(
            select(func.count()).select_from(Report).where(Report.generated_by == user_id)
        )
        return result.scalar_one()

    async def count_all(self) -> int:
        """Return total report count."""
        from sqlalchemy import func

        result = await self._session.execute(select(func.count()).select_from(Report))
        return result.scalar_one()

    async def update_status(
        self,
        report_id: uuid.UUID,
        *,
        status: ReportStatus,
        file_path: str | None = None,
        generated_at: datetime | None = None,
    ) -> Report | None:
        """
        Update report status (and optionally file_path + generated_at).

        Called by the Celery worker when generation completes or fails.
        The caller must commit after calling this method.

        Args:
            report_id:    UUID of the report to update.
            status:       New status value.
            file_path:    Path to the generated file (set on completion).
            generated_at: Timestamp when generation finished.

        Returns:
            Updated Report, or None if not found.
        """
        values: dict[str, object] = {
            "status": status,
            "updated_at": datetime.now(UTC),
        }
        if file_path is not None:
            values["file_path"] = file_path
        if generated_at is not None:
            values["generated_at"] = generated_at

        await self._session.execute(update(Report).where(Report.id == report_id).values(**values))
        await self._session.flush()
        return await self.get_by_id(report_id)
